### ISSUE TITLE
Trouble with XML's external entities parsing

### ISSUE THREAD

**Issue by DenisNovac** [DenisNovac/OVAL-Develop-tool#10]
Issue with external entities parsing blocks work with builder: https://github.com/DenisNovac/OVAL-Develop-tool/issues/3#issuecomment-584031817

Those lines:

```
<modified comment="EDITED oval:org.mitre.oval:obj:6886 - Adding the '&lt;behaviors windows_view=&quot;32_bit&quot; /&gt;' for oval:org.mitre.oval:obj:6886." date="2013-05-07T09:28:00.207-04:00">
              <contributor organization="ALTX-SOFT">Sergey Artykhov</contributor>
            </modified>
```

After saving `XML.save()`:

```
<modified comment='EDITED oval:org.mitre.oval:obj:6886 - Adding the '&lt;behaviors windows_view="32_bit" /&gt;' for oval:org.mitre.oval:obj:6886.' date="2013-05-07T09:28:00.207-04:00">
              <contributor organization="ALTX-SOFT">Sergey Artykhov</contributor>
            </modified>
```

Next loading of saved file gives error:

> Hi everyone. I've read this lines with XML.loadFile(path): <modified comment="EDITED oval:org.mitre.oval:obj:6886 - Adding the '&lt;behaviors windows_view=&quot;32_bit&quot; /&gt;' for oval:org.mitre.oval:obj:6886." date="2013-05-07T09:28:00.207-04:00">               <contributor organization="ALTX-SOFT">Sergey Artykhov</contributor>             </modified>  Then i saved them with XML.save(filepath, xml). Now i want to read this file back, but i can't: Exception in thread "main" org.xml.sax.SAXParseException; lineNumber: 45; columnNumber: 82; Element type "modified" must be followed by either attribute specifications, ">" or "/>". 	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204) 	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178) 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400) 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327) 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1471) 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.seekCloseOfStartTag(XMLDocumentFragmentScannerImpl.java:1433) 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1362) 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710) 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605) 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534) 	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888) 	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824) 	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) 	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216) 	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635) 	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324) 	at scala.xml.factory.XMLLoader.loadXML(XMLLoader.scala:41) 	at scala.xml.factory.XMLLoader.loadXML$(XMLLoader.scala:37) 	at scala.xml.XML$.loadXML(XML.scala:58) 	at scala.xml.factory.XMLLoader.loadFile(XMLLoader.scala:48) 	at scala.xml.factory.XMLLoader.loadFile$(XMLLoader.scala:48) 	at scala.xml.XML$.loadFile(XML.scala:58) 	at composer.OvalIndexer$.$anonfun$indexDefinitions$1(OvalIndexer.scala:43) 	at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:100) 	at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:87) 	at scala.collection.immutable.Vector.map(Vector.scala:119) 	at composer.OvalIndexer$.indexDefinitions(OvalIndexer.scala:40) 	at composer.OvalIndexer$.createIndex(OvalIndexer.scala:30) 	at Main$.main(Main.scala:11) 	at Main.main(Main.scala)

**Comment by DenisNovac** [comment]
Looks like the trouble only affects version 2.0.0-M1, switching to 1.2.0 do the trick.
